name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.2
  easy_localization: ^3.0.0
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.0
  sizer: ^2.0.15
  flutter_svg: ^1.1.6
  connectivity_plus: ^2.3.9
  dio_cache_interceptor: ^3.3.1
  path_provider: ^2.0.11
  dio_cache_interceptor_hive_store: ^3.2.0
  cloud_firestore:
  settings_ui: ^2.0.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  google_maps_flutter: ^2.1.12
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
